# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: build
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github
  workflow_dispatch:
    inputs:
      imageTag:
        description: Image Tag
        required: false
        default: latest
env:
  IMAGE_NAME: go-api
  REGISTRY_HOST: localhost:5000
  REGISTRY_STORAGE_S3_REGION: us-west-2
  REGISTRY_STORAGE_S3_BUCKET: vorprog-container-registry
  TEST_CONTAINER_PORT: 3000
  TEST_HOST_PORT: 3001
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - id: git-checkout
        uses: actions/checkout@v2 # https://github.com/actions/checkout/blob/main/action.yml
      - id: docker-build
        run: |
          sudo docker build $GITHUB_WORKSPACE \
          --build-arg BUILD_COMMIT=$GITHUB_SHA \
          --tag $REGISTRY_HOST/$IMAGE_NAME:$GITHUB_SHA \
          --tag $REGISTRY_HOST/$IMAGE_NAME:latest
      - id: docker-run-test
        run: |
          sudo docker run \
          --env APP_SERVER_PORT=$TEST_CONTAINER_PORT \
          --publish $TEST_HOST_PORT:$TEST_CONTAINER_PORT \
          --name "${GITHUB_REPOSITORY##*/}-test" \
          --detach \
          $IMAGE_NAME:$GITHUB_SHA
          sleep 5 
          curl --verbose --head localhost:$TEST_HOST_PORT
          export CURL_TEST_HTTP_STATUS_CODE=$(curl localhost:$TEST_HOST_PORT --write-out '%{http_code}\n' --silent --output test-response-content.txt)
          if [[ "$CURL_TEST_HTTP_STATUS_CODE" != "200" ]]; then echo "Unexpected http status code $CURL_TEST_HTTP_STATUS_CODE" && exit 1; fi
          echo "Successful HTTP response code $CURL_TEST_HTTP_STATUS_CODE"
          sudo docker rm --force "${GITHUB_REPOSITORY##*/}-test"
      - id: push-image-to-s3
        run: |
          sudo docker run \
          --env REGISTRY_STORAGE=s3 \
          --env REGISTRY_STORAGE_S3_REGION=$REGISTRY_STORAGE_S3_REGION \
          --env REGISTRY_STORAGE_S3_BUCKET=$REGISTRY_STORAGE_S3_BUCKET \
          --detach \
          --publish 80:5000 \
          registry.hub.docker.com/library/registry:latest
          sudo docker push $REGISTRY_HOST/$IMAGE_NAME --all-tags
          sudo docker rmi $IMAGE_NAME $REGISTRY_HOST/$IMAGE_NAME:$GITHUB_SHA $REGISTRY_HOST/$IMAGE_NAME:latest
          sudo docker rm --force registry.hub.docker.com/library/registry:latest
