# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: concurrency-test
on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: Image Tag
        required: false
        default: latest
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
env:
  IMAGE_NAME: ${{github.repository}}
jobs:
  virtual-user-1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --silent ifconfig.me
  virtual-user-2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --silent ifconfig.me
  virtual-user-3:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --silent ifconfig.me
  virtual-user-4:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --silent ifconfig.me
