# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: deploy
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      imageTag:
        description: Image Tag
        required: false
        default: latest
defaults:
  run:
    shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
env:
  IMAGE_NAME: localhost/${{github.repository}}
  HOST_PORT: 80
  APP_SERVER_PORT: 80
  FLUENTD_HOST: fluentd.vorprog.com:24224
  APP_ENVIRONMENT_CONFIGURATION: dev
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - id: cleanup
        run: |
          export EXISTING_CONTAINER_ID=$(sudo docker ps --quiet --filter name="${GITHUB_REPOSITORY##*/}")
          if [[ -z "${EXISTING_CONTAINER_ID-}" ]]; then echo "No existing container named ${GITHUB_REPOSITORY##*/} is running. Exiting current step." && exit 0; fi
          sudo docker inspect $EXISTING_CONTAINER_ID --format 'ID {{ .Id }} {{printf "\n"}}Started at {{ .State.StartedAt }} {{printf "\n"}}Image ID {{ .Image }}'
          sudo docker rm --force $EXISTING_CONTAINER_ID
      - id: pull-image
        run: |
          sudo docker pull $IMAGE_NAME:$GITHUB_SHA
      - id: start-container
        run: |
          sudo docker run \
          --log-driver=fluentd \
          --log-opt fluentd-address=$FLUENTD_HOST \
          --log-opt fluentd-sub-second-precision=true \
          --log-opt tag="docker.{{.ImageName}}.{{.ImageID}}.{{.ID}}" \
          --env APP_ENVIRONMENT_CONFIGURATION=$APP_ENVIRONMENT_CONFIGURATION \
          --env APP_SERVER_PORT=$APP_SERVER_PORT \
          --publish $HOST_PORT:$APP_SERVER_PORT \
          --rm \
          --detach \
          --name "${GITHUB_REPOSITORY##*/}" \
          $IMAGE_NAME:$GITHUB_SHA
